# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7007e74eee55d8ab8f72fb50cc2154be"
name = "Thankyou Block"
handle = "thankyou-block"
application_url = "https://upload-unknown-enables-earn.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = ["https://upload-unknown-enables-earn.trycloudflare.com/auth/callback", "https://upload-unknown-enables-earn.trycloudflare.com/auth/shopify/callback", "https://upload-unknown-enables-earn.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
